### ISSUE TITLE
Texture Handler draws incorrect colors to atlas from greyscale textures

### ISSUE THREAD

**Issue by UselessBullets** [Turnip-Labs/bta-halplibe#35]
### Vanilla minecraft anvil texture which is set to use a greyscale pallet
![image](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/04131e47-723e-47a2-a0a1-e596cb05782e)
### And how it renders ingame
![image](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/9e4d6706-5f48-4c24-be4d-efde7634ca7b)
### Texture dump showing that its incorrect on the atlas itself
![image](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/9e66bfdc-9740-4636-952a-ca9b92ad02bf)

### Texture when its export using an RGB pallet
![image](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/eb03a312-d179-4983-9319-6ec3e74dff04)
![image](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/734882ee-7e90-4808-a866-c46c8e32f453)
![image](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/41be877e-3c68-4c22-ab7a-f13fa1299f58)

### Raw textures used
![anvil](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/646eab2b-e17c-48af-983b-8772354a7d90)
![anvil](https://github.com/Turnip-Labs/bta-halplibe/assets/80850784/fc4bfe69-7c46-4360-840f-bc9ac454f6b4)

**Comment by MartinSVK12** [comment]
Is this relevant still?

**Comment by UselessBullets** [comment]
Probably, I never fixed it and I dont think anyone else did
