### ISSUE TITLE
Custom mod blocks breaks textures when Terrain.png uses textures above 16x (Better than Adventure)

### ISSUE THREAD

**Issue by Kendant** [Turnip-Labs/bta-halplibe#9]
![2023-09-13_18 17 17](https://github.com/Turnip-Labs/bta-halplibe/assets/51292143/583a1918-c706-4ad8-99eb-88e833cdf49f)
![2023-09-13_18 40 03](https://github.com/Turnip-Labs/bta-halplibe/assets/51292143/09a42d40-dedc-41ad-a3fe-1bea86bc5dbf)

Bottom image is rose and cobweb in world.

To recreate, increase Bta's Terrain.png resolution by 200%  with nearest neighbor, use it via texture pack, and install the "Cave Uberhaul!" Mod from the BTA discord.

Cave uberhaul creator was contacted; after discussion "Do you think it's a bug with halplibe then?" "yea pretty sure. I just changed the order in which the custom blocks get registered, the textures are still messed up in 32x but now theres different blocks overlapping with the flowers etc"

![342323423423](https://github.com/Turnip-Labs/bta-halplibe/assets/51292143/06c7563d-7d17-4e92-b84e-996a96dc5545)
![223232323](https://github.com/Turnip-Labs/bta-halplibe/assets/51292143/06b327ad-6c0a-45f2-a64d-514a3e259c38)

The image with the area in red is the 2x scale Terrain.png. The other image with the area in the selection highlight is the area that Terrain.png at it's native resolution overlaps with 2x scale Terrain.png when anchored the top right corner. It's my speculation that the texture placing logic is simply not accounting for the change in resolution scale, and writing in areas that would normally be empty on a 1x scale Terrain.png.

**Comment by MartinSVK12** [comment]
Should be fixed in v2.3.0 (#12)
